Resolved issue #3
toydotgame/old-google pull request #4
Opened 2023-05-18 08:44 UTC by thardwardy

Added '/imghp' and 'images.google' to affected pages.
Replaced vector logo on images search page with image.

2023-05-18 09:32 UTC, toydotgame commented on replace.js
> +	document.getElementsByTagName("svg")[0].outerHTML = '<img class="jfN4p" src="logo" style="background:none" alt="Google" data-atf="1" data-frt="0" width="92" height="30">';
Might update this with a string var for the boilerplate ID and some simpler JS code to identify the HTML `src` and `alt` attributes in a more open way. Matching an exact string is a bit too boilerplate IMO, and I think those `width` and `height` values might be JS controlled (potentially).

2023-05-18 23:33 UTC, toydotgame commented on replace.js
> +	document.getElementsByTagName("svg")[0].outerHTML = '<img class="jfN4p" src="logo" style="background:none" alt="Google" data-atf="1" data-frt="0" width="92" height="30">';
is `document.querySelectorAll("[alt='Google']")` and some integration of `document.getElementsByClassName("jfN4p")` into that (idk how yet) simple enough yet enough selectors to select only the logo SVG/PNG?

2023-05-20 12:05 UTC, toydotgame requested changes
doesnt work bozo L + ratio

2023-05-21 04:56 UTC, thardwardy commented
worked on stuff together in person, big re-write, closing

2023-05-21 04:56 UTC, closed without merging